### ISSUE TITLE
1.7.10: Issue with removal of to high enchanted items

### ISSUE THREAD

**Issue by CanusLupus** [kangarko/Confiscate#116]
Hi,

I encountered and issue with confiscation of to high enchanted items. The scan detect the item in the inventory but it do not get removed and the console and log show an error message.

Removal of banned/over limit items works fine.

Console error message:

```
[09:17:02 INFO]: Taking XXXXXX too high enchant Sharpness 32767 on Bibliocraft Itemslottedbook
[09:17:02 INFO]: Confiscate 2.6.3 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file.
[09:17:02 INFO]: at org.mineacademy.confiscate.lib.fo.ItemUtil.bountifyCapitalized(ItemUtil.java:98)
[09:17:02 INFO]: at org.mineacademy.confiscate.model.Scan.runCommands(Scan.java:746)
[09:17:02 INFO]: at org.mineacademy.confiscate.model.Scan.logAndRunCommands(Scan.java:728)
[09:17:02 INFO]: at org.mineacademy.confiscate.model.Scan.scanUnnaturalAndTooHighEnchants(Scan.java:396)
[09:17:02 INFO]: at org.mineacademy.confiscate.model.Scan.scanEnchants(Scan.java:353)
[09:17:02 INFO]: at org.mineacademy.confiscate.model.Scan.scan(Scan.java:145)
[09:17:02 INFO]: at org.mineacademy.confiscate.model.Scan.scanInventory(Scan.java:119)
[09:17:02 INFO]: at org.mineacademy.confiscate.listener.ScanListener.scanInventory(ScanListener.java:104)
[09:17:02 INFO]: at org.mineacademy.confiscate.listener.ScanListener.lambda$onCommand$0(ScanListener.java:179)
[09:17:02 INFO]: at org.mineacademy.confiscate.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
[09:17:02 INFO]: !-----------------------------------------------------!
[09:17:02 INFO]: !-----------------------------------------------------!
```

Entry in the confiscated error log:

```
------------------------------------[ 15.02.2021 09:14:22 ]-----------------------------------
Confiscate 2.6.3 encountered a NullPointerException
Running Thermos 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: AcceptRules v2.1, PluginConstructorAPI v1.0.52, SimpleBroadcast v1.9.2, KeepItems v1.2, AntiCreeper v4.18.1, PlaceholderAPI v2.10.9, BungeeChatAPI v1.0.1, Craftconomy3 v3.2.1-13814c0-trv139, PlugMan v2.1.7, ConsoleSpamFix v1.8.4, PowerNBT v0.8.9.2, ModDisable v3.0, RewardVoting v6.0.2, WooMinecraft v1.0.10-PR1-B1.7.10-R0.1, CraftingStore v2.6.0, GSONLib vFINAL, dynmap v2.3-112, LuckPerms v5.2.86, WorldEdit v6.1;no_git_id, OpenInv v2.2.7, PluginSpoof v1.0, Essentials vPre2.14.1.3, Offline_Teleporter v0.5, ClearLag v3.1.6, WorldBorder v1.8.1, Votifier v2.7.1, ProtocolLib v3.7.0, Bed v1.0, AutoSaveWorld v4.15, dynmap-mobs v1.3, WorldEditCrashFix v1.0, OpChecker v1.5.0-B33-R6b, FakePlayerFix v2.3, MMode v3.0, AntiForceOP v1.0, Vault v1.4.1-b436, MachinaBanItem v1.1, WorldeditRegions v1.0.2, Dynmap-Essentials v0.80, ChestShop v3.7.18, HolographicDisplays v1.8.8, EssentialsProtect vPre2.14.1.3, KeepDeathDrop v1.0.7, EssentialsSpawn vPre2.14.1.3, Wild v1.53, ShopGUIPlus v1.19.7, RedProtect v7.5.6, NCrateReloaded
H1474302139, UltimateChat v1.9.1, OnTime v4.1.3, SuperVanish v6.2.0, DiscordSRV v1.21.3, Confiscate v2.6.3
----------------------------------------------------------------------------------------------

More Information: 
Failed to execute scheduled task: java.lang.NullPointerException
NullPointerException (Unknown cause)
	 at org.mineacademy.confiscate.lib.fo.ItemUtil.bountifyCapitalized(ItemUtil.java:98)
	 at org.mineacademy.confiscate.model.Scan.runCommands(Scan.java:746)
	 at org.mineacademy.confiscate.model.Scan.logAndRunCommands(Scan.java:728)
	 at org.mineacademy.confiscate.model.Scan.scanUnnaturalAndTooHighEnchants(Scan.java:396)
	 at org.mineacademy.confiscate.model.Scan.scanEnchants(Scan.java:353)
	 at org.mineacademy.confiscate.model.Scan.scan(Scan.java:145)
	 at org.mineacademy.confiscate.model.Scan.scanInventory(Scan.java:119)
	 at org.mineacademy.confiscate.listener.ScanListener.scanInventory(ScanListener.java:104)
	 at org.mineacademy.confiscate.listener.ScanListener.lambda$onCommand$0(ScanListener.java:179)
	 at org.mineacademy.confiscate.lib.fo.remain.CompRunnable$SafeRunnable.run(CompRunnable.java:35)
	 at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	 at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
----------------------------------------------------------------------------------------------
```

Thank you very much in advance for the help.

**Comment by kangarko** [comment]
Thanks will patch soon!

**Comment by CanusLupus** [comment]
Hi,

Thanks for the fast fix unfortunately i had not directly time to test it. The version 2.6.4 is not more loading correctly. It always ends up in the same error.

OK when i setup a fresh server Confiscated is loading by first start (when its also generating the config files) but then by second one its running in to the same error and refuses to load.

```
-----------------------------------[ 17.02.2021 23:22:40 ]-----------------------------------
Confiscate 2.6.4 encountered a FoException
Running Thermos 1.7.10-R0.1-SNAPSHOT and Java 1.8.0_271
Plugins: AcceptRules v2.1, PluginConstructorAPI v1.0.52, SimpleBroadcast v1.9.2, KeepItems v1.2, AntiCreeper v4.18.1, PlaceholderAPI v2.10.9, BungeeChatAPI v1.0.1, Craftconomy3 v3.2.1-13814c0-trv139, PlugMan v2.1.7, ConsoleSpamFix v1.8.4, PowerNBT v0.8.9.2, ModDisable v3.0, RewardVoting v6.0.2, WooMinecraft v1.0.10-PR1-B1.7.10-R0.1, CraftingStore v2.6.0, GSONLib vFINAL, dynmap v2.3-112, LuckPerms v5.2.86, WorldEdit v6.1;no_git_id, OpenInv v2.2.7, PluginSpoof v1.0, Essentials vPre2.14.1.3, Offline_Teleporter v0.5, ClearLag v3.1.6, WorldBorder v1.8.1, Votifier v2.7.1, ProtocolLib v3.7.0, Bed v1.0, AutoSaveWorld v4.15, dynmap-mobs v1.3, WorldEditCrashFix v1.0, OpChecker v1.5.0-B33-R6b, FakePlayerFix v2.3, MMode v3.0, AntiForceOP v1.0, Vault v1.4.1-b436, MachinaBanItem v1.1, WorldeditRegions v1.0.2, Dynmap-Essentials v0.80, ChestShop v3.7.18, HolographicDisplays v1.8.8, EssentialsProtect vPre2.14.1.3, KeepDeathDrop v1.0.7, EssentialsSpawn vPre2.14.1.3, Wild v1.53, ShopGUIPlus v1.19.7, RedProtect v7.5.6, NCrateReloaded
H1474302139, UltimateChat v1.9.1, OnTime v4.1.3, SuperVanish v6.2.0, DiscordSRV v1.21.3, Confiscate v2.6.4
----------------------------------------------------------------------------------------------

More Information: 
Expected human readable time like '1 second', got 'none' instead
FoException Report: Expected human readable time like '1 second', got 'none' instead
	 at org.mineacademy.confiscate.lib.fo.Valid.checkBoolean(Valid.java:81)
	 at org.mineacademy.confiscate.lib.fo.TimeUtil.toTicks(TimeUtil.java:153)
	 at org.mineacademy.confiscate.lib.fo.model.SimpleTime.<init>(SimpleTime.java:19)
	 at org.mineacademy.confiscate.lib.fo.model.SimpleTime.from(SimpleTime.java:39)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlConfig.getTime(YamlConfig.java:965)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.getTime(YamlStaticConfig.java:401)
	 at org.mineacademy.confiscate.settings.Settings.access$4700(Settings.java:29)
	 at org.mineacademy.confiscate.settings.Settings$Confiscate$ItemsNewcomers.init(Settings.java:251)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.invokeMethodsIn(YamlStaticConfig.java:216)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.invokeAll(YamlStaticConfig.java:194)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.loadViaReflection(YamlStaticConfig.java:169)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.access$000(YamlStaticConfig.java:38)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig$1.onLoadFinish(YamlStaticConfig.java:68)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlConfig.loadConfiguration(YamlConfig.java:334)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.createFileAndLoad(YamlStaticConfig.java:254)
	 at org.mineacademy.confiscate.lib.fo.settings.SimpleSettings.load(SimpleSettings.java:41)
	 at org.mineacademy.confiscate.lib.fo.settings.YamlStaticConfig.load(YamlStaticConfig.java:92)
	 at org.mineacademy.confiscate.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:268)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438)
	 at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
Post me your settings please

**Comment by CanusLupus** [comment]
Hi,

it also happen with a completely new generated config (without any changes) like the attached one as soon as i start the server a second time. The first time when the server is generating the config it starts without any problem.

```
# -------------------------------------------------------------------------------------------
# 
#  Your file has been automatically updated at 18.02.2021 08:48:38
#  to Confiscate 2.6.4
# 
#  Unfortunatelly, due to how Bukkit saves all .yml files, it was not possible
#  preserve the documentation comments in your file. We apologize.
# 
#  If you'd like to view the default file, you can either:
#  a) Open the Confiscate-2.6.4.jar with a WinRar or similar
#  b) or, visit: https://github.com/kangarko/Confiscate/wiki
# 
# -------------------------------------------------------------------------------------------

Chest_Room:
  Enabled: true
  Load_After_Server_Starts: false
  Material: BEDROCK
Scan:
  Inventories: false
  On_Command:
  - /warp
  Containers:
    Enabled: true
    Ignored:
    - ANVIL
Ignore:
  Creative_Mode: true
  Worlds:
  - vanilla
  - vanilla_nether
Confiscate:
  Crashable_Items: false
  Clone: false
  Label_Item: true
  Potions:
    Hacked: false
    Infinite: false
    Max_Effect: 10
  Enchants:
    Allow_Strictness: 1
    Lore_Whitelist:
    - A Boss egg|This is a Boss egg
    Supply_With_Unenchanted: false
    Non_Applicable:
      Enabled: false
      Exceptions:
      - THORNS
    Too_High:
      Enabled: true
      Exceptions:
        SILK_TOUCH: 2
  Items:
  - SOIL
  Items_Survival:
  - COMMAND
  - BARRIER
  - STRUCTURE_BLOCK
  - COMMAND_MINECART
  - ENDER_PORTAL
  - ENDER_PORTAL_FRAME
  - PORTAL
  Items_Stacked_Unnaturally:
    Enabled: true
    Exceptions:
    - POTION
  Items_Above:
    DIAMOND_BLOCK: 64
    DIAMOND: 256
    EMERALD_BLOCK: 64
    EMERALD: 256
    IRON_BLOCK: 300
    GOLD_BLOCK: 240
    REDSTONE_BLOCK: 500
    LAPIS_BLOCK: 640
    DRAGON_EGG: 5
    BEACON: 15
    GOLDEN_APPLE:1: 54
  Items_Newcomers:
    Threshold: none
    List:
      DIAMOND_BLOCK: 3
      DIAMOND: 48
      EMERALD_BLOCK: 3
      EMERALD: 32
      IRON_BLOCK: 6
      GOLD_BLOCK: 6
      REDSTONE_BLOCK: 5
      LAPIS_BLOCK: 6
      DRAGON_EGG: 0
      BEACON: 0
  Custom_Items:
  - name: Hacked Potion
    lore: Allows to kill creative players
  - name: '* (.*)(Hacked Spawn Egg)'
    lore: Special spawn egg to lag the server!
After_Confiscating:
  Run_Commands: []
Log:
  Enabled: true
  Exceptions: []
Spy:
  Enabled: true
  Write_To_File: true
  Block: false
  Command_List:
  - /give
  - /i
  - /ban
  - /tempban
  - /gm
  - /gamemode
  - /op
WorldEdit:
  Enabled: true
  Total_Blocks_Limit:
    vip: 1000
    moderators: 20000
  Blocks_Limits:
  - CHEST
  - TRAPPED_CHEST
  - ENDER_CHEST
  - FURNACE
  - BURNING_FURNACE
  - DISPENSER
  - DROPPER
  - HOPPER
  - COMMAND
  - BEACON
  - ANVIL
  - ENCHANTMENT_TABLE
  - JUKEBOX
  - STRUCTURE_BLOCK
  - BREWING_STAND
  - CAULDRON
  - BEDROCK-512
  - BARRIER-512
  - SPONGE
  - MOB_SPAWNER-8
  - DAYLIGHT_DETECTOR
  - ENDER_PORTAL_FRAME
  - DRAGON_EGG-4
  - NOTE_BLOCK
  - IRON_BLOCK-128
  - GOLD_BLOCK-128
  - REDSTONE_BLOCK-128
  - LAPIS_BLOCK-128
  - DIAMOND_BLOCK-64
  - EMERALD_BLOCK-64
  - TNT-24
  - WATER-12
  - STATIONARY_WATER-12
  - STATIONARY_LAVA-8
  - LAVA-8
  - FIRE-12
  - RAILS
  - POWERED_RAIL
  - DETECTOR_RAIL
  - ACTIVATOR_RAIL
  - LEVER
  - STONE_BUTTON
  - WOOD_BUTTON
  - REDSTONE_TORCH_ON
  - WOOD_PLATE
  - IRON_PLATE
  - STONE_PLATE
  - GOLD_PLATE
  - SAPLING
  - YELLOW_FLOWER
  - RED_ROSE
  - WATER_LILY
  - DOUBLE_PLANT
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - CARPET
  - TORCH
  - VINE
  - SNOW
  - TRIPWIRE_HOOK
  - TRAP_DOOR
  - IRON_TRAPDOOR
  - REDSTONE_WIRE
  - CROPS
  - CARROT
  - POTATO
  Wait_Threshold: 30 seconds
Command_Aliases:
- confiscate
- c
Prefix: '&7C &8//&7'
Locale: en
Notify_Updates: true
Notify_Promotions: true
Log_Lag_Over_Milis: 100
Debug: []
Version: 5
```

**Comment by kangarko** [comment]
I am so sorry, I fixed this right away, please download the next version.

**Comment by CanusLupus** [comment]
Thanks a lot all is now working fine :)
