### ISSUE TITLE
1.12.2: Confiscate not starting.

### ISSUE THREAD

**Issue by SladeHazard** [kangarko/Confiscate#121]
The plugin does not load because I'm using older version of shop which is the only version supporting 1.12 atm.

[00:00:50] [Server thread/INFO]: java.lang.NoClassDefFoundError: com/snowgears/shop/ShopType
[00:00:50] [Server thread/INFO]: at org.mineacademy.confiscate.Confiscate.onPluginStart(Confiscate.java:104)
[00:00:50] [Server thread/INFO]: at org.mineacademy.confiscate.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:293)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:00:50] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[00:00:50] [Server thread/INFO]: java.lang.ClassNotFoundException: com.snowgears.shop.ShopType
[00:00:50] [Server thread/INFO]: at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
[00:00:50] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[00:00:50] [Server thread/INFO]: at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
[00:00:50] [Server thread/INFO]: at org.mineacademy.confiscate.Confiscate.onPluginStart(Confiscate.java:104)
[00:00:50] [Server thread/INFO]: at org.mineacademy.confiscate.lib.fo.plugin.SimplePlugin.onEnable(SimplePlugin.java:293)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[00:00:50] [Server thread/INFO]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[00:00:50] [Server thread/INFO]: at java.lang.Thread.run(Thread.java:748)
[00:00:50] [Server thread/INFO]:     ___                  _
[00:00:50] [Server thread/INFO]:    / _ \  ___  _ __  ___| |
[00:00:50] [Server thread/INFO]:   | | | |/ _ \| '_ \/ __| |
[00:00:50] [Server thread/INFO]:   | |_| | (_) | |_) \__ \_|
[00:00:50] [Server thread/INFO]:    \___/ \___/| .__/|___(_)
[00:00:50] [Server thread/INFO]:              |_|
[00:00:50] [Server thread/INFO]: !-----------------------------------------------------!
[00:00:50] [Server thread/INFO]: Error loading Confiscate v3.0.0, plugin is disabled!
[00:00:50] [Server thread/INFO]: Running on 1.12.2-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_292
[00:00:50] [Server thread/INFO]: !-----------------------------------------------------!
[00:00:50] [Server thread/INFO]: Error: com.snowgears.shop.ShopType
[00:00:50] [Server thread/INFO]: !-----------------------------------------------------!
[00:00:50] [Server thread/INFO]: [Confiscate] Disabling Confiscate v3.0.0

**Comment by kangarko** [comment]
Thanks for reporting, sorry for the delay. I will make the error ignored silently, however you wont be able to use that hook since their API has changed.
