### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by Eneshai** [kangarko/Confiscate#13]
Hello,

I get every half hour this error in the console when a player is online. 
Can you please help me? 

-------------------------------------------------------------------------------------------------------------------

[15:20:18 ERROR]: Could not pass event InventoryOpenEvent to Confiscate v1.4.5
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:750) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:736) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.EntityPlayer.openTileEntity(EntityPlayer.java:673) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.BlockWorkbench.interact(SourceFile:33) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:525) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException

-------------------------------------------------------------------------------------------------------------------

Thank you. :)

**Comment by Eneshai** [comment]
Can it be that a another plugin is incompatible with Confiscate or is this a another Error?

**Comment by kangarko** [comment]
Hey,

I cannot find any trace to "me.kangarko" code in the error, so I cannot track it down. Please look up whether this is the whole error, and try to see if the error has been recorded to errors.log file in Confiscate/ folder.

**Comment by Eneshai** [comment]
Hello, thanks for the response.

I found it:
-------------------------------------------------------------------------------------------------------------------
at me.kangarko.confiscate. .nul...\\............lpT2.transient(SourceFile:43) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lpT2.protected(SourceFile:36) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lPt2.protected(SourceFile:34) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LPt1.transient(SourceFile:508) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LPt1.super(SourceFile:188) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LPt1.transient(SourceFile:167) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LPt1.protected(SourceFile:125) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LPt1.protected(SourceFile:107) ~[?:?]
at me.kangarko.confiscate. .nul...\\............Lpt1.onChestOpen(SourceFile:64) ~[?:?]
at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
... 20 more
-------------------------------------------------------------------------------------------------------------------
Is this the right one?

**Comment by kangarko** [comment]
Please try the latest version & let me know if it was fixed :)

**Comment by Eneshai** [comment]
Error is still present. :(

**Comment by kangarko** [comment]
Please re-post the error. The obfuscation mappings change each release so it may now be a different one.

**Comment by Eneshai** [comment]
Yes of course:

----------------------------------------------------------------------------------------------------------------------

[20:36:53 ERROR]: Could not pass event InventoryOpenEvent to Confiscate v1.4.6
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:750) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:736) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.EntityPlayer.openTileEntity(EntityPlayer.java:673) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.BlockWorkbench.interact(SourceFile:33) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PlayerInteractManager.a(PlayerInteractManager.java:525) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:890) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:55) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PacketPlayInUseItem.a(SourceFile:11) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [craftbukkit.jar:git-Spigot-c3e4052-1953f52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
at me.kangarko.confiscate. .nul...\\............LpT2.transient(SourceFile:49) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LpT2.protected(SourceFile:42) ~[?:?]
at me.kangarko.confiscate. .nul...\\............LPt2.protected(SourceFile:34) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lpT1.transient(SourceFile:525) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lpT1.super(SourceFile:192) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lpT1.transient(SourceFile:168) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lpT1.protected(SourceFile:126) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lpT1.protected(SourceFile:108) ~[?:?]
at me.kangarko.confiscate. .nul...\\............lPt1.onChestOpen(SourceFile:64) ~[?:?]
at sun.reflect.GeneratedMethodAccessor141.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-c3e4052-1953f52]
... 20 more

-------------------------------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
I think I have fixed it, please test out with the new version (not the one from today, but the next one that I will release tomorrow)

**Comment by Eneshai** [comment]
Thank you. I will test it when the new version release. :)

**Comment by kangarko** [comment]
Hey, unfortunately I had to travel suddenly. I will release it on Monday the 7th :)

**Comment by Eneshai** [comment]
No problem. Wish you a good journey. :)

**Comment by kangarko** [comment]
I have released it and am closing this issue. Please remind me if it occurs again.
