### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yeongpin** [kangarko/Confiscate#15]
my computer can loading
`[22:13:16] [Server thread/INFO]: [Confiscate] Enabling Confiscate v1.4.6
[22:13:16] [Server thread/INFO]: [0;37;1m____ ____ _  _ ____ _ ____ ____ ____ ___ ____ [m
[22:13:16] [Server thread/INFO]: [0;37;1m|    |  | |\ | |___ | [__  |    |__|  |  |___ [m
[22:13:16] [Server thread/INFO]: [0;37;22m|___ |__| | \| |    | ___] |___ |  |  |  |___ [m
[22:13:16] [Server thread/INFO]:  [m
[22:13:17] [Server thread/INFO]: [0;36;22mHooked into[0;30;1m: [0;37;1mEssentials, PlaceholderAPI, Vault, WorldEdit, WorldGuard[m
[22:13:17] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;33;1mYou have not yet configured your chest room![m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;1mPlease run [0;37;22m/c room tool [0;37;1mand select where[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;1mthe cornerstone of the room shall be![m
[22:13:17] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[22:13:17] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;22m[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;22mConfiscate 1.4.6 premium[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;22m[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;22mFor documentation and reporting bugs, please visit[m
[22:13:17] [Server thread/INFO]:  [0;31;1m[0;37;22mhttps://github.com/kangarko/Confiscate[m
[22:13:17] [Server thread/INFO]: [0;37;22m*-----------------------------------------------*[m
[22:13:17] [Server thread/INFO]:  [m
[22:13:17] [Server thread/INFO]: [0;37;1mConfiscate initialization done. Took 21 ms.[m
[22:13:17] [Server thread/INFO]: [0;37;22m______________________________________________________________[m
[22:13:17] [Server thread/INFO]:  [m`
but my server vpn cant loading
`[22:16:20] [Server thread/INFO]: Confiscate 1.4.6 encountered a Nul! Please check your error.log and report this issue with the information in that file.[m
[22:16:20] [Server thread/ERROR]: Error occurred while enabling Confiscate v1.4.6 (Is it up to date?)
me.kangarko.confiscate. .nul...\\............Nul: Report / Forgot to call HookManazer.check()
	at me.kangarko.confiscate. .nul...\\............PrN.protected(SourceFile:18) ~[?:?]
	at me.kangarko.confiscate. .nul...\\............cOm6.onEnable(SourceFile:123) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.2.jar:git-Paper-817]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.2.jar:git-Paper-817]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.2.jar:git-Paper-817]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.2.jar:git-Paper-817]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.2.jar:git-Paper-817]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:409) [patched_1.10.2.jar:git-Paper-817]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:374) [patched_1.10.2.jar:git-Paper-817]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:328) [patched_1.10.2.jar:git-Paper-817]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:275) [patched_1.10.2.jar:git-Paper-817]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:575) [patched_1.10.2.jar:git-Paper-817]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]`

**Comment by kangarko** [comment]
Please update your version.
