### ISSUE TITLE
[07:49:40 INFO]: This server is running Pufferfish version git-Pufferfish-72 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8f05a00 on HEAD) : ShopGUIPlus API changed

### ISSUE THREAD

**Issue by TypicalShavonne** [kangarko/Confiscate#150]
ShopGUIPlus API changed in the lastestverrsion ,confiscate need to update the API path

**Comment by TypicalShavonne** [comment]
`[07:49:11 ERROR]: Could not pass event ShopPostTransactionEvent to Confiscate v3.2.8
java.lang.NoSuchMethodError: 'net.brcdev.shopgui.shop.ShopItem net.brcdev.shopgui.shop.ShopTransactionResult.getShopItem()'
        at org.mineacademy.confiscate.hook.ShopGUIHook.onShopTransaction(ShopGUIHook.java:17) ~[Confiscate-3.2.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1141.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-72]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.brcdev.shopgui.shop.ShopManager.handleItemSellAll(ShopManager.java:1212) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.clickAmountSelectionGui(PlayerListener.java:427) ~[ShopGUIPlus-1.78.0.jar:?]
        at net.brcdev.shopgui.listener.PlayerListener.onInventoryClick(PlayerListener.java:141) ~[ShopGUIPlus-1.78.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1119.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:git-Pufferfish-72]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2862) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1402) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1379) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:318) ~[pufferfish-1.18.2.jar:git-Pufferfish-72]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by kangarko** [comment]
Thanks. I tried updating however I dont have access to said premium plugin, it should work on the next version tho.

**Comment by TypicalShavonne** [comment]
> Thanks. I tried updating however I dont have access to said premium plugin, it should work on the next version tho.

https://github.com/brcdev-minecraft/shopgui-api

**Comment by kangarko** [comment]
Thanks, should work from the next version.
