### ISSUE TITLE
1.19.2: Changed settings set settings file to null

### ISSUE THREAD

**Issue by Greazi-Times** [kangarko/Confiscate#151]
So the issue that I am having is that when I have changed the settings it makes the file empty.
```
[09:26:09 INFO]: [Confiscate] Enabling Confiscate v3.3.4
[09:26:09 INFO]: ____ ____ _  _ ____ _ ____ ____ ____ ___ ____
[09:26:09 INFO]: |    |  | |\ | |___ | [__  |    |__|  |  |___
[09:26:09 INFO]: |___ |__| | \| |    | ___] |___ |  |  |  |___
[09:26:09 INFO]:   
[09:26:09 INFO]: [PlaceholderAPI] Successfully registered expansion: confiscate [3.3.4]
[09:26:09 INFO]: [DiscordSRV] DiscordSRV is up-to-date. (819b02508abe8879cfc2a513fc6cea383b70b5c5)
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: The option Confiscate.Crashable_Item is no
[09:26:09 INFO]: longer necessary on Minecraft 1.13+ and
[09:26:09 INFO]: was disabled to prevent false catches.
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: Error loading plugins/Confiscate/settings.yml: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 ERROR]: Confiscate 3.3.4 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.19.2-R0.1-SNAPSHOT and Java 17.0.2
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: Failed to load static settings class org.mineacademy.confiscate.settings.Settings
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 ERROR]: Confiscate 3.3.4 encountered a NullPointerException! Please check your error.log and report this issue with the information in that file. Running Purpur 1.19.2-R0.1-SNAPSHOT and Java 17.0.2
[09:26:09 INFO]: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlComments.write(YamlComments.java:150)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlComments.writeComments(YamlComments.java:122)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlConfig.saveToString(YamlConfig.java:214)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.FileConfig.save(FileConfig.java:1311)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.FileConfig.save(FileConfig.java:1279)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.FileConfig.load(FileConfig.java:1207)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlStaticConfig.loadConfiguration(YamlStaticConfig.java:239)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.SimpleSettings.onLoad(SimpleSettings.java:37)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:88)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:213)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:82)
[09:26:09 INFO]:        at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:327)
[09:26:09 INFO]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[09:26:09 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[09:26:09 INFO]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
[09:26:09 INFO]:     ___                  _
[09:26:09 INFO]:    / _ \  ___  _ __  ___| |
[09:26:09 INFO]:   | | | |/ _ \| '_ \/ __| |
[09:26:09 INFO]:   | |_| | (_) | |_) \__ \_|
[09:26:09 INFO]:    \___/ \___/| .__/|___(_)
[09:26:09 INFO]:              |_|
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: Error loading Confiscate v3.3.4, plugin is disabled!
[09:26:09 INFO]: Running on 1.19.2-R0.1-SNAPSHOT (v1_19_R1) & Java 17.0.2
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: Error: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
[09:26:09 INFO]: !-----------------------------------------------------!
[09:26:09 INFO]: [Confiscate] Disabling Confiscate v3.3.4
```

Error message from error.log;
```
------------------------------------[ 03.10.2022 09:26:09 ]-----------------------------------
Confiscate 3.3.4 encountered a NullPointerException
Running Purpur 1.19.2-R0.1-SNAPSHOT and Java 17.0.2
Plugins: PlaceholderAPI v2.11.2, spark v1.9.40, ViaVersion v4.4.2, floodgate v2.2.0-SNAPSHOT (b73-4f36112), ViaBackwards v4.4.2, ImmortalTags v2.1.0, LuckPerms v5.4.46, ProtocolLib v5.0.0-SNAPSHOT-b600, SkinsRestorer v14.2.3, Vault v1.7.3-b131, HeadDatabase v4.17.0, LiteBans v2.10.4, Multiverse-Core v4.3.1-b861, FastAsyncWorldEdit v2.4.7-SNAPSHOT-282;87f6806, TAB v3.1.5, HubParkour v2.7.1, WorldGuard v7.0.7+216b061, Spartan vPhase 484.1, Citizens v2.0.30-SNAPSHOT (build 2705), CMILib v1.2.3.6, PremiumVanish v2.7.20, DiscordSRV v1.26.0, Plan v5.5 build 1971, Confiscate v3.3.4, CMI v9.2.4.3, BungeeTabListPlus v3.5.2, ChatControlRed v10.14.0
----------------------------------------------------------------------------------------------

More Information: 
Failed to load static settings class org.mineacademy.confiscate.settings.Settings
NullPointerException Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlComments.write(YamlComments.java:150)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlComments.writeComments(YamlComments.java:122)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlConfig.saveToString(YamlConfig.java:214)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.FileConfig.save(FileConfig.java:1311)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.FileConfig.save(FileConfig.java:1279)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.FileConfig.load(FileConfig.java:1207)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlConfig.loadConfiguration(YamlConfig.java:173)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlStaticConfig.loadConfiguration(YamlStaticConfig.java:239)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.SimpleSettings.onLoad(SimpleSettings.java:37)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.settings.YamlStaticConfig.load(YamlStaticConfig.java:88)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.plugin.AutoRegisterScanner.registerSettings(AutoRegisterScanner.java:213)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.plugin.AutoRegisterScanner.scanAndRegister(AutoRegisterScanner.java:82)
	 at Confiscate-3.3.4.jar//org.mineacademy.confiscate.lib.plugin.SimplePlugin.onEnable(SimplePlugin.java:327)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:596)
	 at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:510)
----------------------------------------------------------------------------------------------
```

Here is my settings file;
https://hastebin.com/sopenajili.yaml

**Comment by kangarko** [comment]
Having a look in 24h!

**Comment by kangarko** [comment]
Should be solved in the next version

**Comment by Greazi-Times** [comment]
Great I will wait for the update 🙏🏻

**Comment by kangarko** [comment]
Sorry for a late reply, just checking in, let me know if that was solved for you :)
