### ISSUE TITLE
Error in console when trying to confiscate player items

### ISSUE THREAD

**Issue by sanjar12345** [kangarko/Confiscate#16]
`[15:58:58] [Server thread/INFO]: [0;30;1mConfiscate [0;37;22m[0;31;1mTaking 204x of KungKong's Iron Block above limit 150x[m
[15:58:58] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to Confiscate v1.5.0
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:753) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.EntityPlayer.openContainer(EntityPlayer.java:706) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.BlockChest.interact(SourceFile:341) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:483) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: UUID cannot be null
at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.getOfflinePlayer(CraftServer.java:1323) ~[spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.bukkit.Bukkit.getOfflinePlayer(Bukkit.java:745) ~[spigot.jar:git-Spigot-7d78b81-a6d8fa2]
at org.yi.acru.bukkit.Lockette.Lockette.getProtectedOwner(Lockette.java:754) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........COM3.const(SourceFile:1172) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........coM3.do(SourceFile:453) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........LPt1.const(SourceFile:660) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.native(SourceFile:597) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.const(SourceFile:547) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.const(SourceFile:528) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.const(SourceFile:493) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.const(SourceFile:464) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.volatile(SourceFile:309) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.const(SourceFile:134) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lpT1.const(SourceFile:115) ~[?:?]
at me.kangarko.confiscate. .nul...\\...........lPt1.onChestOpen(SourceFile:68) ~[?:?]
at sun.reflect.GeneratedMethodAccessor104.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-7d78b81-a6d8fa2]
... 19 more
[15:58:58] [Craft Scheduler Thread - 6/INFO]: [Statz debug] [0;34;1mSave Statz `database.[m``

Hi! 

Awesome plugin you have, seem to have this tiny issue though.

I'm running 1.12 spigot, 1.50 version of your plugin, thanks for the help! :D

**Comment by kangarko** [comment]
Thank you for your report!

Hey, unfortunately I had to travel suddenly. I will release a fix on Monday the 7th :)

**Comment by kangarko** [comment]
New version has been released. Closing.
