### ISSUE TITLE
Getting an error at plugin load / cannot use plugin

### ISSUE THREAD

**Issue by Towelie** [kangarko/Confiscate#18]
Please advise:
[05:56:42] [Server thread/INFO]: [Confiscate] Disabling Confiscate v1.5.3
[05:56:42] [Server thread/WARN]: java.lang.NoClassDefFoundError: me/kangarko/confiscate/ /nul///\\///////////nul
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........nUl.const(SourceFile:38)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........nUl.<init>(SourceFile:18)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........pRN.const(SourceFile:14)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........coM2.const(SourceFile:68)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........CoM2.long(SourceFile:124)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........aux.const(SourceFile:34)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........CoM2.const(SourceFile:55)
[05:56:42] [Server thread/WARN]: at me.kangarko.confiscate. .nul...\\...........cOM6.onEnable(SourceFile:94)
[05:56:42] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:56:42] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[05:56:42] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[05:56:42] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[05:56:42] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
[05:56:42] [Server thread/WARN]: at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
[05:56:42] [Server thread/WARN]: at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
[05:56:42] [Server thread/WARN]: at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[05:56:42] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[05:56:42] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[05:56:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[05:56:42] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
[05:56:42] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
[05:56:42] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
[05:56:42] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[05:56:42] [Server thread/WARN]: at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[05:56:42] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[05:56:42] [Server thread/INFO]: [0;31;1m _ _ _ [m
[05:56:42] [Server thread/INFO]: [0;31;1m | | | | ___ ___ _ __ ___| |[m
[05:56:42] [Server thread/INFO]: [0;31;1m | |_| |/ _ \ / _ \| '_ \/ __| |[m
[05:56:42] [Server thread/INFO]: [0;31;1m | _ | (_) | (_) | |_) \__ \_|[m
[05:56:42] [Server thread/INFO]: [0;31;22m |_| |_|\___/ \___/| .__/|___(_)[m
[05:56:42] [Server thread/INFO]: [0;31;22m |_| [m
[05:56:42] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[05:56:42] [Server thread/INFO]: [0;31;1mError loading Confiscate v1.5.3, plugin is disabled![m
[05:56:42] [Server thread/INFO]: [0;31;1mRunning on 1.12.1-R0.1-SNAPSHOT (v1_12_R1) & Java 1.8.0_131[m
[05:56:42] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m
[05:56:42] [Server thread/INFO]: [0;31;1mError: me/kangarko/confiscate/ /nul///\\///////////nul[m
[05:56:42] [Server thread/INFO]: [0;31;22m!-----------------------------------------------------![m

**Comment by Towelie** [comment]
NOTE: If the plugin is loaded by restarting the server, this error shows up instead: [06:41:45] [Server thread/INFO]:  [0;31;1mThe enum 'EventPriority' does not contain 'MON?TOR'! Available values: LOWEST, LOW, NORMAL, HIGH, HIGHEST, MONITOR[m

**Comment by kangarko** [comment]
Please redownload the version.
