### ISSUE TITLE
Error with Confiscate 1.5.8

### ISSUE THREAD

**Issue by Eneshai** [kangarko/Confiscate#22]
Got this Error with Confiscate 1.5.8.:

https://pastebin.com/tKH99Bse

Got this with 1.5.8. 
1.5.7 do not make errors.

Thank you :)

**Comment by klugemonkey** [comment]
Similar error with 1.5.8 on 1.12.2...

`Could not pass event InventoryMoveItemEvent to Confiscate v1.5.8
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.TileEntityHopper.s(TileEntityHopper.java:217) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.TileEntityHopper.o(TileEntityHopper.java:134) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.TileEntityHopper.e(TileEntityHopper.java:119) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1503) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_144]
        at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_144]
        at me.kangarko.confiscate. .nul...\\...........CoM4.onInventoryInteract(SourceFile:175) ~[Confiscate-1.5.8.jar:?]
        at sun.reflect.GeneratedMethodAccessor81.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2-custom.jar:git-Spigot-93e20b3-9ab758c]
        ... 13 more
`

**Comment by Eneshai** [comment]
Solved with 1.5.9. Thank you. :)
