### ISSUE TITLE
Startup error (1.8.8)

### ISSUE THREAD

**Issue by Mxra** [kangarko/Confiscate#28]
So I just purchased the plugin, I thought your work with ChatControlPro was phenomenal, so I purchased this.

_SNIP_

There's the error.log, here's the console error on startup:
_SNIP_

**EDIT**
_SNIP_

**Comment by Mxra** [comment]
**Edit Followup**

Here's the config that I had to manually set it to:
```
Chest_Room:
  Enabled: true
  Material: BEDROCK

Scan:
  Inventories: true
  When_Clicking: true
  On_Command:
    - /warp
  Containers:
    Enabled: true
    Ignored: []

Ignore:
  Creative_Mode: true
  Worlds: []

Confiscate: 
  Crashable_Items: true
  Clone: false
  Potions:
    Hacked: true
    Infinite: false
  Enchants: 
    Non_Applicable:
      Enabled: false
      Exceptions:
    Too_High:
      Enabled: true
      Exceptions:
    Allow_Strictness: 0
    Supply_With_Unenchanted: true
  Items: []
  Items_Survival:
    - BEDROCK
    - BARRIER
  Items_Stacked_Unnaturally:
    Enabled: true
    Exceptions: []
  Items_Above:
  Items_Newcomers:
    List:
    Threshold: 1 hour

After_Confiscating:
  Run_Commands: []

Log:
  Enabled: true
  Exceptions: []

Spy:
  Enabled: true
  Write_To_File: true
  Block: false
  Command_List:
    - /give
    - /i
    - /ban
    - /tempban
    - /gm
    - /gamemode
    - /op

WorldEdit:
  Enabled: false
  Total_Blocks_Limit:
  Blocks_Limits:
  Wait_Threshold: 30 seconds

Command_Aliases: [confiscate]
Notify_Updates: true
Debug: false
Debugger: []
Serialization_Number: ""
Version: 3
```

And here's the result of that...
```
28.12 04:16:08 [Server] INFO [Confiscate] Enabling Confiscate v1.7.5
28.12 04:16:08 [Server] INFO ____ ____ _ _ ____ _ ____ ____ ____ ___ ____
28.12 04:16:08 [Server] INFO | | | |\ | |___ | [__ | |__| | |___
28.12 04:16:08 [Server] INFO |___ |__| | \| | | ___] |___ | | | |___
28.12 04:16:08 [Server] INFO Update settings.yml at 'WorldEdit.Total_Blocks_Limit.vip' -> '1000'
28.12 04:16:08 [Server] INFO Update settings.yml at 'WorldEdit.Total_Blocks_Limit.moderators' -> '20000'
28.12 04:16:08 [Server] INFO Update settings.yml at 'WorldEdit.Blocks_Limits' -> '[CHEST, TRAPPED_CHEST, ENDER_CHEST, FURNACE, BURNING_FURNACE, DISPENSER, DROPPER, HOPPER, COMMAND, BEACON, ANVIL, ENCHANTMENT_TABLE, JUKEBOX, STRUCTURE_BLOCK, BREWING_STAND, CAULDRON, BEDROCK-512, BARRIER-512, SPONGE, MOB_SPAWNER-8, DAYLIGHT_DETECTOR, ENDER_PORTAL_FRAME, DRAGON_EGG-4, NOTE_BLOCK, IRON_BLOCK-128, GOLD_BLOCK-128, REDSTONE_BLOCK-128, LAPIS_BLOCK-128, DIAMOND_BLOCK-64, EMERALD_BLOCK-64, TNT-24, WATER-12, STATIONARY_WATER-12, STATIONARY_LAVA-8, LAVA-8, FIRE-12, RAILS, POWERED_RAIL, DETECTOR_RAIL, ACTIVATOR_RAIL, LEVER, STONE_BUTTON, WOOD_BUTTON, REDSTONE_TORCH_ON, WOOD_PLATE, IRON_PLATE, STONE_PLATE, GOLD_PLATE, SAPLING, YELLOW_FLOWER, RED_ROSE, WATER_LILY, DOUBLE_PLANT, BROWN_MUSHROOM, RED_MUSHROOM, CARPET, TORCH, VINE, SNOW, TRIPWIRE_HOOK, TRAP_DOOR, IRON_TRAPDOOR, REDSTONE_WIRE, CROPS, CARROT, POTATO]'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.DIAMOND_BLOCK' -> '3'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.DIAMOND' -> '48'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.EMERALD_BLOCK' -> '3'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.EMERALD' -> '32'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.IRON_BLOCK' -> '6'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.GOLD_BLOCK' -> '6'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.REDSTONE_BLOCK' -> '5'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.LAPIS_BLOCK' -> '6'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.DRAGON_EGG' -> '0'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Newcomers.List.BEACON' -> '0'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.DIAMOND_BLOCK' -> '64'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.DIAMOND' -> '256'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.EMERALD_BLOCK' -> '64'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.EMERALD' -> '256'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.IRON_BLOCK' -> '300'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.GOLD_BLOCK' -> '240'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.REDSTONE_BLOCK' -> '500'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.LAPIS_BLOCK' -> '640'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.DRAGON_EGG' -> '5'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.BEACON' -> '15'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Items_Above.GOLDEN_APPLE:1' -> '54'
28.12 04:16:08 [Server] INFO Update settings.yml at 'Confiscate.Enchants.Non_Applicable.Exceptions' -> '[THORNS]'
28.12 04:16:08 [Server] INFO Confiscate 1.7.5 encountered a com2! Please check your error.log and report this issue with the information in that file.
28.12 04:16:08 [Server] INFO java.lang.reflect.InvocationTargetException
28.12 04:16:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.12 04:16:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
28.12 04:16:08 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28.12 04:16:08 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:98)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ŕł(SourceFile:79)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9$1.ă(SourceFile:30)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.LPt6.ă(SourceFile:124)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:129)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.lPT2.á(SourceFile:36)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:56)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COm4.onEnable(SourceFile:170)
28.12 04:16:08 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
28.12 04:16:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
28.12 04:16:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
28.12 04:16:08 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
28.12 04:16:08 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
28.12 04:16:08 [Server] INFO at java.lang.Thread.run(Thread.java:748)
28.12 04:16:08 [Server] INFO me.kangarko.confiscate. .nul.com2: Report / Invalid enchantment 'THORNS'! For valid names, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.Lpt3.ă(SourceFile:20)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.LPT8.ťß(SourceFile:96)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.lPT2.â¤Łá(SourceFile:359)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.lPT2.áŹ(SourceFile:30)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.lPT2$transient$protected.init(SourceFile:174)
28.12 04:16:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
28.12 04:16:08 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
28.12 04:16:08 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
28.12 04:16:08 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:98)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ŕł(SourceFile:79)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9$1.ă(SourceFile:30)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.LPt6.ă(SourceFile:124)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:129)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.lPT2.á(SourceFile:36)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COM9.ă(SourceFile:56)
28.12 04:16:08 [Server] INFO at me.kangarko.confiscate. .nul.COm4.onEnable(SourceFile:170)
28.12 04:16:08 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
28.12 04:16:08 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
28.12 04:16:08 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
28.12 04:16:08 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
28.12 04:16:08 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
28.12 04:16:08 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
28.12 04:16:08 [Server] INFO at java.lang.Thread.run(Thread.java:748)
28.12 04:16:08 [Server] INFO _ _ _
28.12 04:16:08 [Server] INFO | | | | ___ ___ _ __ ___| |
28.12 04:16:08 [Server] INFO | |_| |/ _ \ / _ \| '_ \/ __| |
28.12 04:16:08 [Server] INFO | _ | (_) | (_) | |_) \__ \_|
28.12 04:16:08 [Server] INFO |_| |_|\___/ \___/| .__/|___(_)
28.12 04:16:08 [Server] INFO |_|
28.12 04:16:08 [Server] INFO !-----------------------------------------------------!
28.12 04:16:08 [Server] INFO Error loading Confiscate v1.7.5, plugin is disabled!
28.12 04:16:08 [Server] INFO Running on 1.8.8-R0.2-SNAPSHOT (v1_8_R3) & Java 1.8.0_151
28.12 04:16:08 [Server] INFO !-----------------------------------------------------!
28.12 04:16:08 [Server] INFO Error: Report / Invalid enchantment 'THORNS'! For valid names, see: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html
28.12 04:16:08 [Server] INFO !-----------------------------------------------------!
28.12 04:16:08 [Server] INFO [Confiscate] Disabling Confiscate v1.7.5
```

**Comment by Mxra** [comment]
Ignore this, I'm a tool...
