### ISSUE TITLE
Out of bounds exception when viewing inv for offline player...

### ISSUE THREAD

**Issue by mrcoffee1026** [kangarko/Confiscate#38]
```
[16:26:46] [Server thread/INFO]: mr_coffee1026 issued server command: /c inv view agent_null
[16:26:46] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: -106
[16:26:46] [Server thread/WARN]: 	at java.util.Arrays$ArrayList.set(Arrays.java:3846)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NonNullList.set(SourceFile:51)
[16:26:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventoryCustom$MinecraftInventory.setItem(CraftInventoryCustom.java:107)
[16:26:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setItem(CraftInventory.java:96)
[16:26:46] [Server thread/WARN]: 	at me.kangarko.confiscate. .nul.throw.㢂ḱ(SourceFile:66)
[16:26:46] [Server thread/WARN]: 	at me.kangarko.confiscate. .nul.super.㢂ḱ(SourceFile:37)
[16:26:46] [Server thread/WARN]: 	at me.kangarko.confiscate.protected.㢂ḱ(SourceFile:274)
[16:26:46] [Server thread/WARN]: 	at me.kangarko.confiscate.protected.㢂ḱ(SourceFile:142)
[16:26:46] [Server thread/WARN]: 	at me.kangarko.confiscate. .nul.auX.onCommand(SourceFile:53)
[16:26:46] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[16:26:46] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[16:26:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[16:26:46] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[16:26:46] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[16:26:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[16:26:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

```

I get this a lot but not all the time.

**Comment by kangarko** [comment]
Sorry for the delay.

Thank you for reporting, I did some changes and could not reproduce it from my testing. I also added more informative error messages. Please test the new version.
