### ISSUE TITLE
Confiscate suddenly stopped working

### ISSUE THREAD

**Issue by x1p** [kangarko/Confiscate#44]
This evening. All of a sudden CHC stopped working. Luckily there was an update for that.
But Confiscate stopped working too. And there does not seem to be an update. Why is it terminated?

[23:39:08] [Server thread/ERROR]: Could not load 'plugins/Confiscate-1.8.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.ClassFormatError: Unknown constant tag 0 in class file me/kangarko/confiscate/Confiscate
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:327) ~[spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:248) [spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:305) [spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassFormatError: Unknown constant tag 0 in class file me/kangarko/confiscate/Confiscate
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_161]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_161]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:148) ~[spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_161]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot-SuSe-1.12.2.20f-jar:git-Spigot-4bd94dc-fb414fe]
	... 6 more

**Comment by kangarko** [comment]
I am investigating this. Please let me know if it happens again (you will need to re-download the jar).
