### ISSUE TITLE
Console spam after update v1.9.0

### ISSUE THREAD

**Issue by CypherPhyre** [kangarko/Confiscate#54]
[15:33:16] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Confiscate v1.9.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitRegisteredListener.java:35) ~[PerWorldPluginsPremium.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerList.onPlayerJoin(PlayerList.java:344) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:163) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.LoginListener.b(LoginListener.java:150) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.LoginListener.Y_(LoginListener.java:54) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:115) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:93) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.onPlayerJoin(SourceFile:73) ~[Confiscate-1.9.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	... 15 more
[15:33:18] [Server thread/INFO]: [WorldBorder] Teleport cause: UNKNOWN
[15:33:18] [Server thread/INFO]: tombolton7[/86.152.26.120:50442] logged in with entity id 35217 at ([world]212.76750622901827, 66.0, 1074.9005233880512)
[15:33:49] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to Confiscate v1.9.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitRegisteredListener.java:35) ~[PerWorldPluginsPremium.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:777) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityPlayer.openContainer(EntityPlayer.java:831) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.BlockChest.interact(SourceFile:219) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.IBlockData.interact(SourceFile:281) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:492) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1242) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.㢂ḱ(SourceFile:121) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.onChestOpen(SourceFile:68) ~[Confiscate-1.9.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	... 21 more
[15:33:49] [Server thread/WARN]: [Confiscate] Task #331367 for Confiscate v1.9.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:115) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:93) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:168) ~[Confiscate-1.9.0.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[15:34:22] [Server thread/WARN]: [Confiscate] Task #349320 for Confiscate v1.9.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:115) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:93) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:168) ~[Confiscate-1.9.0.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[15:34:26] [Server thread/WARN]: [Confiscate] Task #357816 for Confiscate v1.9.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:115) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:93) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:168) ~[Confiscate-1.9.0.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[15:34:27] [Server thread/WARN]: [Confiscate] Task #359892 for Confiscate v1.9.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:115) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:93) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:168) ~[Confiscate-1.9.0.jar:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[15:34:49] [Server thread/INFO]: [0;33;1mtombolton7 [0;37;22mwas playing with matches[m
[15:34:49] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Confiscate v1.9.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:308) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at com.heirteir.perworldpluginspremium.registeredlisteners.BukkitRegisteredListener.callEvent(BukkitRegisteredListener.java:35) ~[PerWorldPluginsPremium.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:434) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityPlayer.die(EntityPlayer.java:493) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:1055) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:799) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:622) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.Entity.W(Entity.java:452) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityLiving.W(EntityLiving.java:210) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.Entity.tick(Entity.java:333) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2026) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityHuman.tick(EntityHuman.java:151) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.EntityPlayer.playerTick(EntityPlayer.java:381) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.PlayerConnection.Y_(PlayerConnection.java:140) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.aufdemrand.denizen.nms.impl.packets.handlers.AbstractListenerPlayIn_v1_13_R2.Y_(AbstractListenerPlayIn_v1_13_R2.java:76) [denizen-1.0.3-SNAPSHOT.jar:?]
	at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:231) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:120) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:998) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.ItemStack.getI18NDisplayName()Ljava/lang/String;
	at me.kangarko.confiscate. .nul.cOm8.㢂ḱ(SourceFile:32) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ύଃ㕔(SourceFile:526) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:142) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.lPt4.ⲯ(SourceFile:115) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.㢂ḱ(SourceFile:93) ~[Confiscate-1.9.0.jar:?]
	at me.kangarko.confiscate. .nul.com6.onPlayerDeath(SourceFile:78) ~[Confiscate-1.9.0.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:304) ~[spigot-1.13.1.jar:git-Spigot-f6a273b-8ab46ff]
	... 24 more

**Comment by kangarko** [comment]
Thanks, fixed in the next version.,
