### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by ArtelGG** [kangarko/Confiscate#59]
This NPE was caused after I used the reload command, only changing the settings I listed below from default.
All version information is in the log.

```
------------------------------------[ 29.01.2019 23:52:06 ]-----------------------------------
Confiscate 1.10.0 encountered a NullPointerException
Running CraftBukkit 1.8.8-R0.1-SNAPSHOT and Java 1.8.0_202
Plugins: CoreProtect v2.12.0, LuckPerms v4.3.73, FastAsyncWorldEdit v19.01.12-dc2d277-1245-22.0.7, ChatControl v5.7.3, ViaVersion v1.6.0, WorldBorder v1.8.6, NametagEdit v4.4.0, Vault v1.7.1-b91, ProtocolLib v4.4.0, ViaRewind v1.3.13, WorldEdit v6.1.9;caf0ad9, Essentials v2.15.0.1, EssentialsProtect v2.15.0.1, EssentialsGeoIP v2.15.0.1, EssentialsAntiBuild v2.15.0.1, LiteBans v2.3.14, EssentialsSpawn v2.15.0.1, WorldGuard v6.1.3-SNAPSHOT;c904242, Confiscate v1.10.0
----------------------------------------------------------------------------------------------

More Information: 
Error reloading Confiscate 1.10.0
NullPointerException (Unknown cause)
	 at me.kangarko.confiscate. .nul.PRN.?(SourceFile:110)
	 at me.kangarko.confiscate. .nul.CoM7.????(SourceFile:533)
	 at me.kangarko.confiscate. .nul.CoM7.????????(SourceFile:499)
	 at me.kangarko.confiscate.protected.??(SourceFile:242)
	 at me.kangarko.confiscate. .nul.cOM9.onCommand(SourceFile:61)
	 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	 at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629)
----------------------------------------------------------------------------------------------
```

The only settings changed are as follows:
```
Command_Aliases:
- confiscate
- conf

Notify_Promotions: false
```
**P.S: It generated as a configuration file with no comments due to the setting changes at startup for version specific options, perhaps you could find a better workaround for that?**

**Comment by kangarko** [comment]
Fixed in the next version, sorry about this
