### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by GermanMinersNET** [kangarko/Confiscate#63]
In the new version 1.11 I get the following error.
I suppose it's related to the update that 1.13 material names should be supported better, but unfortunately the downward compatibility for minecraft version 1.12 doesn't work anymore.

More Information: 
Invalid material 'BURNING_FURNACE'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Please note that many names have changed in 1.13!)
CoM1 Report / Invalid material 'BURNING_FURNACE'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Please note that many names have changed in 1.13!)
	 at me.kangarko.confiscate. .nul.cOM9.㢂ḱ(SourceFile:23)
	 at me.kangarko.confiscate. .nul.Lpt6.ⲯ(SourceFile:88)
	 at me.kangarko.confiscate. .nul.Lpt6.㢂ḱ(SourceFile:82)
	 at me.kangarko.confiscate. .nul.Con.㗈(SourceFile:384)
	 at me.kangarko.confiscate. .nul.Con.ࡃᔸቖ㕆(SourceFile:31)
	 at me.kangarko.confiscate. .nul.Con$void.init(SourceFile:339)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at me.kangarko.confiscate. .nul.com4.㢂ḱ(SourceFile:136)
	 at me.kangarko.confiscate. .nul.com4.㦟ᐮ㩀ヲㇲṯ᧐Ȭྲ(SourceFile:103)
	 at me.kangarko.confiscate. .nul.com4$1.㢂ḱ(SourceFile:38)
	 at me.kangarko.confiscate. .nul.LpT4.ⲯ(SourceFile:131)
	 at me.kangarko.confiscate. .nul.com4.ⲯ(SourceFile:167)
	 at me.kangarko.confiscate. .nul.Com1.ⲯ(SourceFile:24)
	 at me.kangarko.confiscate. .nul.com4.㢂ḱ(SourceFile:64)
	 at me.kangarko.confiscate. .nul.LpT6.onEnable(SourceFile:214)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
	 at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
----------------------------------------------------------------------------------------------

**Comment by kangarko** [comment]
Hey, sorry for the delay, that has been fixed in 1.11.1
