### ISSUE TITLE
[bug] Can not generate new chest

### ISSUE THREAD

**Issue by momoservertw** [kangarko/Confiscate#75]
The chest room in world "cheat", and the cheat player is in world "world". 
After the player open a chest, this error occour.
`
[03:12:45 INFO]: Taking 59x of test_008's BEACON above limit 5x
[03:12:45 ERROR]: Could not pass event InventoryOpenEvent to Confiscate v2.2.8
java.lang.NullPointerException: null
        at org.mineacademy.confiscate.lib.fo.model.PRN.native(SourceFile:2246) ~[?:?]
        at org.mineacademy.confiscate.lib.fo.model.PRN.const(SourceFile:2123) ~[?:?]
        at org.mineacademy.confiscate.lib.fo.model.CoM3.transient(SourceFile:1184) ~[?:?]
        at org.mineacademy.confiscate.int. .j.native(SourceFile:790) ~[?:?]
        at org.mineacademy.confiscate.int. .k.strictfp(SourceFile:693) ~[?:?]
        at org.mineacademy.confiscate.int. .k.private(SourceFile:636) ~[?:?]
        at org.mineacademy.confiscate.int. .k.const(SourceFile:614) ~[?:?]
        at org.mineacademy.confiscate.int. .k.const(SourceFile:580) ~[?:?]
        at org.mineacademy.confiscate.int. .k.for(SourceFile:510) ~[?:?]
        at org.mineacademy.confiscate.int. .k.transient(SourceFile:340) ~[?:?]
        at org.mineacademy.confiscate.int. .k.native(SourceFile:140) ~[?:?]
        at org.mineacademy.confiscate.int. .k.const(SourceFile:121) ~[?:?]
        at org.mineacademy.confiscate.int. .i.onChestOpen(SourceFile:70) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor922.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-196]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1174) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.EntityPlayer.openContainer(EntityPlayer.java:1148) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.BlockChest.interact(BlockChest.java:202) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IBlockData.interact(IBlockData.java:226) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:487) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1361) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1013) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:990) ~[patched_1.14.4.jar:git-Paper-196]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:923) ~[patched_1.14.4.jar:git-Paper-196]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

This is my config.
https://pastebin.com/XUGFZjZh

Multiverse-Core Version: 4.1.0-SNAPSHOT-b772
Confiscate version: 2.2.8
Paper version git-Paper-196 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by kangarko** [comment]
This seems to me like an issue in WorldGuard or WorldEdit, ensure you use the latest versions from:

- https://dev.bukkit.org/projects/worldguard
- https://dev.bukkit.org/projects/worldedit

From August 2019.

Also update your Confiscate to the upcoming version please.
