### ISSUE TITLE
Confiscate has not worked since purchase

### ISSUE THREAD

**Issue by Tradie18** [kangarko/Confiscate#80]
[INFO] [Confiscate] Enabling Confiscate v2.3.2

[INFO] ____ ____ _ _ ____ _ ____ ____ ____ ___ ____

[INFO] | | | |\ | |___ | [__ | |__| | |___

[INFO] |___ |__| | \| | | ___] |___ | | | |___

[INFO]

[INFO] Hooked into: mcMMO

[INFO] __________________________________________________________

[INFO]

[INFO] Confiscate 2.3.2 premium

[INFO]

[INFO] For documentation and reporting bugs, please visit

[INFO] https://github.com/kangarko/Confiscate

[INFO]

[INFO] Initialization done. Took 7 ms.

[INFO] __________________________________________________________

[INFO]

[INFO] java.lang.NullPointerException

[INFO] at github.scarsz.discordsrv.util.LangUtil$InternalMessage.toString(LangUtil.java:816)

[INFO] at github.scarsz.discordsrv.api.ApiManager.subscribe(ApiManager.java:63)

[INFO] at org.mineacademy.confiscate.lib.fo.model.LpT7$protected.<init>(SourceFile:213)

[INFO] at org.mineacademy.confiscate.int. .Com3.onEnable(SourceFile:313)

[INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)

[INFO] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)

[INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)

[INFO] at java.lang.Thread.run(Thread.java:813)

[INFO] _ _ _

[INFO] | | | | ___ ___ _ __ ___| |

[INFO] | |_| |/ _ \ / _ \| '_ \/ __| |

[INFO] | _ | (_) | (_) | |_) \__ \_|

[INFO] |_| |_|\___/ \___/| .__/|___(_)

[INFO] |_|

[INFO] !-----------------------------------------------------!

[INFO] Error loading Confiscate v2.3.2, plugin is disabled!

[INFO] Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 1.8.0_212

[INFO] !-----------------------------------------------------!

[INFO] Error: Unable to get the error message, search above.

[INFO] !-----------------------------------------------------!

[INFO] [Confiscate] Disabling Confiscate v2.3.2

I've read all threads and watched setup tutorials, none of which have helped.

**Comment by Tradie18** [comment]
nvm resolved it myself
