### ISSUE TITLE
1.14 Giving errors

### ISSUE THREAD

**Issue by Gagels** [kangarko/Confiscate#84]
____ ____ _  _ ____ _ ____ ____ ____ ___ ____
[12:16:48] [Server thread/INFO]: |    |  | |\ | |___ | [__  |    |__|  |  |___
[12:16:48] [Server thread/INFO]: |___ |__| | \| |    | ___] |___ |  |  |  |___
[12:16:48] [Server thread/INFO]:   
[12:16:48] [Server thread/INFO]: Confiscate 2.3.8 encountered a cOm1! Please check your error.log and report this issue with the information in that file.
[12:16:48] [Server thread/INFO]: !-----------------------------------------------------!
[12:16:48] [Server thread/INFO]: Error loading configuration in settings.yml!
[12:16:48] [Server thread/INFO]: Problematic section: Confiscate
[12:16:48] [Server thread/INFO]: Problem: org.mineacademy.confiscate.int. .cOm1: Report / Invalid material 'REDSTONE_DUST'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Note that names change across MC versions!) (see below for more)
[12:16:48] [Server thread/INFO]: Plugin is now disabled.
[12:16:48] [Server thread/INFO]: !-----------------------------------------------------!
[12:16:48] [Server thread/INFO]: [Confiscate] Disabling Confiscate v2.3.8
[12:16:48] [Server thread/INFO]: org.mineacademy.confiscate.int. .cOm1: Report / Invalid material 'REDSTONE_DUST'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Note that names change across MC versions!)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .lpT9.const(SourceFile:57)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .Com9.const(SourceFile:1554)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .Com9.native(SourceFile:1577)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .Lpt6.const(SourceFile:51)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .COM2.k(SourceFile:406)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .COM2.throws(SourceFile:32)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .COM2$transient$super.init(SourceFile:240)
[12:16:48] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:16:48] [Server thread/INFO]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:16:48] [Server thread/INFO]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:16:48] [Server thread/INFO]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .m.native(SourceFile:182)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .m.const(SourceFile:159)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .m.transient(SourceFile:134)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .m$1.const(SourceFile:56)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .k.const(SourceFile:299)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .m.R(SourceFile:220)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .j.a_(SourceFile:39)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .m.const(SourceFile:80)
[12:16:48] [Server thread/INFO]: 	at org.mineacademy.confiscate.int. .lPT2.onEnable(SourceFile:253)
[12:16:48] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[12:16:48] [Server thread/INFO]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352)
[12:16:48] [Server thread/INFO]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417)
[12:16:48] [Server thread/INFO]: 	at java.lang.Thread.run(Thread.java:748)
[12:16:48] [Server thread/INFO]:   _   _                       _
[12:16:48] [Server thread/INFO]:   | | | | ___   ___  _ __  ___| |
[12:16:48] [Server thread/INFO]:   | |_| |/ _ \ / _ \| '_ \/ __| |
[12:16:48] [Server thread/INFO]:   |  _  | (_) | (_) | |_) \__ \_|
[12:16:48] [Server thread/INFO]:   |_| |_|\___/ \___/| .__/|___(_)
[12:16:48] [Server thread/INFO]:                     |_|
[12:16:48] [Server thread/INFO]: !-----------------------------------------------------!
[12:16:48] [Server thread/INFO]: Error loading Confiscate v2.3.8, plugin is disabled!
[12:16:48] [Server thread/INFO]: Running on 1.14.4-R0.1-SNAPSHOT (v1_14_R1) & Java 1.8.0_202
[12:16:48] [Server thread/INFO]: !-----------------------------------------------------!
[12:16:48] [Server thread/INFO]: Error: Report / Invalid material 'REDSTONE_DUST'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Note that names change across MC versions!)
[12:16:48] [Server thread/INFO]: !-----------------------------------------------------!

default config is used

**Comment by JavaFactoryDev** [comment]
Hey Gagels,

Thank you for using Confiscate & Reporting this issue here.
The exception already tells you what to do.

> : Error: Report / Invalid material 'REDSTONE_DUST'! For valid names, see: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html (Note that names change across MC versions!)

Regards,
- Leonhard from MineAcademy
