### ISSUE TITLE
Confiscate, error when starting up server (plugin disabled)

### ISSUE THREAD

**Issue by Luisikoman** [kangarko/Confiscate#96]
Something goes wrong with ES language loading it in config (LOCALE: es)

More Information: 
Default 'messages_es.yml' lacks a String at 'Commands.List.Label_Required'
aV Report / Default 'messages_es.yml' lacks a String at 'Commands.List.Label_Required'
	 at org.mineacademy.confiscate.int. .ah.a(SourceFile:57)
	 at org.mineacademy.confiscate.int. .cO.i(SourceFile:1504)
	 at org.mineacademy.confiscate.int. .cO.h(SourceFile:490)
	 at org.mineacademy.confiscate.int. .cO.f(SourceFile:667)
	 at org.mineacademy.confiscate.int. .cQ.ba(SourceFile:316)
	 at org.mineacademy.confiscate.int. .z.ar(SourceFile:11)
	 at org.mineacademy.confiscate.int. .z$b$b.init(SourceFile:197)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.mineacademy.confiscate.int. .cQ.b(SourceFile:182)
	 at org.mineacademy.confiscate.int. .cQ.a(SourceFile:159)
	 at org.mineacademy.confiscate.int. .cQ.g(SourceFile:134)
	 at org.mineacademy.confiscate.int. .cQ$1.a(SourceFile:56)
	 at org.mineacademy.confiscate.int. .cO.b(SourceFile:222)
	 at org.mineacademy.confiscate.int. .cQ.aM(SourceFile:216)
	 at org.mineacademy.confiscate.int. .cM.a_(SourceFile:39)
	 at org.mineacademy.confiscate.int. .cQ.a(SourceFile:80)
	 at org.mineacademy.confiscate.int. .bM.onEnable(SourceFile:253)
	 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	 at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
	 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:352)
	 at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:311)

**Comment by JavaFactoryDev** [comment]
Hmm are u using the latest version?

**Comment by JavaFactoryDev** [comment]
Doesn't reply

**Comment by kangarko** [comment]
Identified, fixed.
